replicaCount: 1

image:
  repository: ghcr.io/giannisstathoudakis/theoros-server
  pullPolicy: IfNotPresent
  tag: "prod-v2.0.0"

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080