replicaCount: 1

image:
  repository: ghcr.io/giannisstathoudakis
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  name: ""

rbac:
  create: trues

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080