apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-wildcard-tls
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  secretName: lab-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.kublab.org"
  dnsNames:
  - "*.kublab.org"
  - "kublab.org"