apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "theoros.fullname" . }}
  labels:
    {{- include "theoros.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "theoros.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "theoros.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "theoros.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          
          volumeMounts:
            - name: db-storage
              mountPath: /data
            - name: tmp-dir
              mountPath: /tmp
            - name: bootstrap-secret
              mountPath: /etc/theoros/bootstrap
              readOnly: true
              
          ports:
            - name: grpc
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
              
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ include "theoros.fullname" . }}-db-pvc
        - name: tmp-dir
          emptyDir: {}
        - name: bootstrap-secret
          secret:
            secretName: theoros-cred