apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: theoros-cred-token
  namespace: theoros
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: theoros-cred
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials: "{{ .username }}:{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: Theoros
        property: username
    - secretKey: password
      remoteRef:
        key: Theoros
        property: password