syntax = "proto3";

package theoros.v1;

option go_package = "github.com/GiannisStathoudakis/Theoros/gen/theoros/v1";

service KubernetesService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc ExecuteCommand(CommandRequest) returns (CommandResponse);
  rpc InteractiveExec(ExecRequest) returns (stream ExecResponse);
  
  // User Management
  rpc GenerateToken(GenerateTokenRequest) returns (GenerateTokenResponse);
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);

  // Autocompletion Engine
  rpc GetCompletions(GetCompletionsRequest) returns (GetCompletionsResponse);
}

message LoginRequest {
  string token = 1;
}

message LoginResponse {
  string token = 1;
}

message CommandRequest {
  string action = 1;
  string resource = 2;
  string name = 3;
  string namespace = 4;
  repeated string flags = 5;
}

message CommandResponse {
  string output = 1;
}

message ExecRequest {
  string action = 1;
  string resource = 2;
  string name = 3;
  string namespace = 4;
  repeated string flags = 5;
  bytes stdin = 6; 
}

message ExecResponse {
  bytes stdout = 1;
  bytes stderr = 2;
}

// User Management Messages
message GenerateTokenRequest {
  string username = 1;
}

message GenerateTokenResponse {
  string token = 1;
}

message ListUsersRequest {}

message ListUsersResponse {
  repeated string usernames = 1;
}

message DeleteUserRequest {
  string username = 1;
}

message DeleteUserResponse {
  string message = 1;
}

message GetCompletionsRequest {
  repeated string args = 1; 
}

message GetCompletionsResponse {
  repeated string suggestions = 1; 
}