syntax = "proto3";

package theoros.v1;

option go_package = "github.com/GiannisStathoudakis/Theoros/gen/theoros/v1";

service KubernetesService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc ExecuteCommand(CommandRequest) returns (CommandResponse);
  rpc InteractiveExec(stream ExecRequest) returns (stream ExecResponse);
  
  // User Management
  rpc GenerateToken(GenerateTokenRequest) returns (GenerateTokenResponse);
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);
}

message LoginRequest {
  string token = 1;
}

message LoginResponse {
  string token = 1;
}

message CommandRequest {
  string action = 1;
  string resource = 2;
  string name = 3;
  string namespace = 4;
  repeated string flags = 5;
}

message CommandResponse {
  string output = 1;
}

message ExecRequest {
  string pod_name = 1;
  string namespace = 2;
  bytes stdin_data = 3; 
}

message ExecResponse {
  bytes stdout_data = 1;
  bytes stderr_data = 2;
}

// User Management Messages
message GenerateTokenRequest {
  string username = 1;
}

message GenerateTokenResponse {
  string token = 1;
}

message ListUsersRequest {}

message ListUsersResponse {
  repeated string usernames = 1;
}

message DeleteUserRequest {
  string username = 1;
}

message DeleteUserResponse {
  string message = 1;
}